# Dependencies
markdown:         kramdown
highlighter:      rouge
encoding:         utf-8

# Setup
title:            Yash Chandak
tagline:          'Personal Webpage'
description:      'y[lastname]@cs.umass.edu'
url:              https://yashchandak.github.io/yashchandak
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
email:            y[lastname]@cs.umass.edu
author:
  name:           'Yash Chandak'
  url:            yashchandak.github.io

paginate:         5
paginate_path:    '/blog/page:num/'
                  # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
sidebar_blog_link:  '/blog/'     # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
sidebar_about_link: '/about.html'

# Avoid MM/DD/YYYY format for blog post links
#permalink: /:title.html

github:
  repo:             https://github.com/yashchandak

twitter:            https://twitter.com/chandakyash13
facebook:           https://www.facebook.com/yashchandak.13
linkedin:           https://www.linkedin.com/in/yashchandak/
scholar:            https://scholar.google.com/citations?user=AsgUcSEAAAAJ&hl=en&oi=ao

# Include all files under '_pages' as files in root directory
include: ['_pages']

google_analytics:   UA-128250681-1

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: yashchandak

## Jekyll-scholar settings
#plugins: ['jekyll/scholar']
#scholar:
#  style: apa
#  locale: en
#
#  sort_by: year
#  order: descending
#  bibliography_list_tag: ul
#
#  source: _bibliography
#  repository: pdf
#  bibliography: references
#  bibliography_template: bibliography
#
#  replace_strings: true
#
#  details_dir:    bibliography
#  details_layout: bibtex.html
#  details_link:   Details
#
#  query: "@*"
